sudo: required
services:
    - docker
language: cpp
compiler: gcc
cache: ccache
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then
           brew update;
           brew install openssl cmake ccache;
          export PATH="/usr/local/opt/ccache/libexec:$PATH";
      fi
script:
    - if [ $TRAVIS_OS_NAME == osx ]; then
          mkdir build;
          cd build;
          cmake ..;
          make;
          make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then
          mkdir build;
          docker build -t cpp-ipfs/cpp-multihash .;
          docker run -v $PWD:/work/source/ -v $PWD/build:/work/build
             --privileged -it cpp-ipfs/cpp-multihash;
      fi
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
