sudo: required
services: 
    - docker
language: cpp
compiler: g++
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then 
           brew update 
        && brew unlink  openssl 
        && brew install openssl 
        && brew link --force openssl
        && brew unlink  cmake
        && brew install cmake 
        && brew link --force cmake;
      fi
script: 
    - if [ $TRAVIS_OS_NAME == osx ]; then 
             mkdir build 
          && cd build 
          && cmake .. 
          && make 
          && make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then 
             docker build -t jbrooker/cpp-multihash . 
          && docker run -v $PWD:/work/source/ --privileged -it jbrooker/cpp-multihash;
      fi
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
