sudo: required

services:
    - docker

language: cpp

compiler: gcc

cache:
  directories:
  - $HOME/.hunter
  - $HOME/.ccache

install:
    - if [ $TRAVIS_OS_NAME == osx ]; then
           brew update;
           brew install openssl cmake ccache;
           export PATH="/usr/local/opt/ccache/libexec:$PATH";
      fi

script:
    - if [ $TRAVIS_OS_NAME == osx ]; then
          mkdir build;
          cd build;
          cmake ..;
          make;
          make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then
          mv -v $HOME/build/cpp-ipfs/cpp-multihash ${HOME}/src;
          docker run -v ${HOME}:/root \
                     -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" \
                     -e TRAVIS_BRANCH="$TRAVIS_BRANCH" \
                     --privileged -it lockblox/orthodox;
      fi

branches:
    only:
    - master

notification:
    email: true

os:
- linux
- osx
