sudo: required
services: 
    - docker
language: cpp
compiler: g++
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then 
           brew update 
        && brew unlink  openssl 
        && brew install openssl 
        && brew link --force openssl
        && brew unlink  cmake
        && brew install cmake 
        && brew link --force cmake;
      fi
script: 
    - test $TRAVIS_OS_NAME == osx \ 
      && mkdir build && cd build && cmake .. && make && make test;
    - test $TRAVIS_OS_NAME == linux \
      && docker build -t cpp-multihash . \
      && docker run -v $PWD:/work/source/ --privileged -it cpp-multihash;
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
