sudo: required
services:
    - docker
language: cpp
compiler: gcc
cache: ccache
install:
    - if [ $TRAVIS_OS_NAME == osx ]; then
           brew update;
           brew install openssl cmake ccache;
          export PATH="/usr/local/opt/ccache/libexec:$PATH";
      fi
script:
    - if [ $TRAVIS_OS_NAME == osx ]; then
          mkdir build;
          cd build;
          cmake ..;
          make;
          make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then
          docker run -v $PWD:/work/source/ --entrypoint "/home/quality/build.sh"
             --privileged -it lockblox/orthodox
             "/work/source/ipfs/multi"
             "/work/source";
      fi
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
