sudo: required

services:
    - docker

language: cpp

compiler: gcc

cache:
  directories:
  - $HOME/.hunter
  - $HOME/.ccache

before_install:
  - pip install --user cpp-coveralls

install:
    - if [ $TRAVIS_OS_NAME == osx ]; then
           brew update;
           brew install openssl cmake ccache;
           export PATH="/usr/local/opt/ccache/libexec:$PATH";
      fi

script:
    - if [ $TRAVIS_OS_NAME == osx ]; then
          mkdir build;
          cd build;
          cmake ..;
          make;
          make test;
      fi
    - if [ $TRAVIS_OS_NAME == linux ]; then
          docker run -v $PWD:/root/src:ro
                     -v $HOME:/root --privileged -it lockblox/orthodox;
      fi

after_success:
  - coveralls --gcov llvm-cov --gcov-options gcov --verbose  -i multihash

branches:
    only:
    - master

notification:
    email: true

os:
- linux
- osx
